FROM openjdk:8u102-jre

MAINTAINER Luke Granger-Brown <docker@lukegb.com>

LABEL io.openshift.expose-services="8080:http" \
      io.openshift.tags="sbt"

# Defines the S2I scripts location
LABEL io.openshift.s2i.scripts-url=image:///usr/local/s2i \
      io.openshift.s2i.assemble-input-files="/opt/app"
# Copy the S2I scripts in
COPY ./.s2i/bin/ /usr/local/s2i

# Specify the ports for the final image
EXPOSE 8080

# Create app user
RUN mkdir /opt/app-root && \
    useradd -u 1001 -r -g 0 -d ${HOME} -s /sbin/nologin \
      -c "Default Application User" default && \
    chown -R 1001:0 /opt/app-root
ENV HOME=/opt/app-root/src \
    PATH=/opt/app-root/src/bin:/opt/app-root/bin:$PATH
USER 1001
